services:
  postiz:
    image: 'ghcr.io/gitroomhq/postiz-app:v2.11.3'
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: 'https://socialshare.gooddoglabs.net'
      FRONTEND_URL: 'https://socialshare.gooddoglabs.net'
      NEXT_PUBLIC_BACKEND_URL: 'https://socialshare.gooddoglabs.net/api'
      JWT_SECRET: 'CHANGE_ME_run_openssl_rand_hex_32'
      DATABASE_URL: 'postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local'
      REDIS_URL: 'redis://postiz-redis:6379'
      BACKEND_INTERNAL_URL: 'http://localhost:3000'
      IS_GENERAL: 'true'
      DISABLE_REGISTRATION: 'false'
      RUN_CRON: 'true'
      STORAGE_PROVIDER: local
      UPLOAD_DIRECTORY: /uploads
      NEXT_PUBLIC_UPLOAD_DIRECTORY: /uploads
      X_API_KEY: ''
      X_API_SECRET: ''
      LINKEDIN_CLIENT_ID: ''
      LINKEDIN_CLIENT_SECRET: ''
      REDDIT_CLIENT_ID: ''
      REDDIT_CLIENT_SECRET: ''
      GITHUB_CLIENT_ID: ''
      GITHUB_CLIENT_SECRET: ''
      BEEHIIVE_API_KEY: ''
      BEEHIIVE_PUBLICATION_ID: ''
      THREADS_APP_ID: ''
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - 'traefik.http.routers.postiz.rule=Host(`socialshare.gooddoglabs.net`)'
      - traefik.http.routers.postiz.entryPoints=https
      - traefik.http.routers.postiz.tls=true
      - traefik.http.routers.postiz.tls.certresolver=letsencrypt
      - traefik.http.services.postiz.loadbalancer.server.port=5000
      - 'traefik.http.routers.postiz-http.rule=Host(`socialshare.gooddoglabs.net`)'
      - traefik.http.routers.postiz-http.entryPoints=http
      - traefik.http.routers.postiz-http.middlewares=redirect-to-https
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    networks:
      - default
      - coolify

  postiz-postgres:
    image: 'postgres:17-alpine'
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - default

  postiz-redis:
    image: 'redis:7.2'
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - default

volumes:
  postgres-volume:
  postiz-redis-data:
  postiz-config:
  postiz-uploads:

networks:
  default:
  coolify:
    external: true
