services:
  postiz:
    image: 'ghcr.io/gitroomhq/postiz-app:latest'
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: 'https://socialshare.gooddoglabs.net'
      FRONTEND_URL: 'https://socialshare.gooddoglabs.net'
      NEXT_PUBLIC_BACKEND_URL: 'https://socialshare.gooddoglabs.net/api'
      JWT_SECRET: 'CHANGE_ME_run_openssl_rand_hex_32'
      DATABASE_URL: 'postgresql://postiz-user:postiz-password@postiz-postgres:5432/postiz-db-local'
      REDIS_URL: 'redis://postiz-redis:6379'
      BACKEND_INTERNAL_URL: 'http://localhost:3000'
      TEMPORAL_ADDRESS: 'temporal:7233'
      IS_GENERAL: 'true'
      DISABLE_REGISTRATION: 'false'
      RUN_CRON: 'true'
      STORAGE_PROVIDER: local
      UPLOAD_DIRECTORY: /uploads
      NEXT_PUBLIC_UPLOAD_DIRECTORY: /uploads
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - 'traefik.http.routers.postiz.rule=Host(`socialshare.gooddoglabs.net`)'
      - traefik.http.routers.postiz.entryPoints=https
      - traefik.http.routers.postiz.tls=true
      - traefik.http.routers.postiz.tls.certresolver=letsencrypt
      - traefik.http.services.postiz.loadbalancer.server.port=5000
      - 'traefik.http.routers.postiz-http.rule=Host(`socialshare.gooddoglabs.net`)'
      - traefik.http.routers.postiz-http.entryPoints=http
      - traefik.http.routers.postiz-http.middlewares=redirect-to-https
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    networks:
      - default
      - coolify
      - temporal-network

  postiz-postgres:
    image: 'postgres:17-alpine'
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-password
      POSTGRES_USER: postiz-user
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - default

  postiz-redis:
    image: 'redis:7.2'
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - default

  temporal-elasticsearch:
    container_name: temporal-elasticsearch
    image: elasticsearch:7.17.27
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    networks:
      - temporal-network
    expose:
      - 9200
    volumes:
      - temporal-es-data:/var/lib/elasticsearch/data

  temporal-postgresql:
    container_name: temporal-postgresql
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    networks:
      - temporal-network
    expose:
      - 5432
    volumes:
      - temporal-pg-data:/var/lib/postgresql/data

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.28.1
    restart: always
    depends_on:
      - temporal-postgresql
      - temporal-elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=temporal-elasticsearch
      - ES_VERSION=v7
      - TEMPORAL_NAMESPACE=default
    networks:
      - temporal-network
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

volumes:
  postgres-volume:
  postiz-redis-data:
  postiz-config:
  postiz-uploads:
  temporal-es-data:
  temporal-pg-data:

networks:
  default:
  coolify:
    external: true
  temporal-network:
    driver: bridge
